- name: Bug - create group
  group:
    name: bug
    state: present

- name: Bug - create user
  user:
    name: bug
    group: root
    state: present
    comment: "beli bug"
    password: "{{ bug_passwd }}"

- name: Bug - add public key 
  authorized_key:
    user: bug
    key: "{{ item }}"
  with_file:
    - bug/b4pi.pub
    - bug/buglapind.pub
    - bug/chromebook.pub
    - bug/elitebug.pub
    - bug/laptop-office.pub
    - bug/macmini.pub

- name: Bug - add sudoers file
  copy:
    src: bug/sudoers_bug
    dest: /etc/sudoers.d/bug
    owner: root
    group: root
    mode: 0440
