- name: create group bug
  tags: groups,bug,users
  group:
    name: bug
    state: present

- name: create user bug
  tags: bug,sudo,users
  user:
    name: bug
    group: bug
    state: present
    comment: "beli bug"
    password: "{{ bug_passwd }}"
