- name: Vidura - create user  
  user:
    name: vidura
    group: root

- name: Vidura - add public key
  authorized_key:
    user: vidura
    key: "{{ item }}"
  with_file:
    - vidura/vidura.pub

- name: Vidura - add sudoers file
  copy:
    src: vidura/sudoers_vidura
    dest: /etc/sudoers.d/vidura
    owner: root
    group: root
    mode: 0440

- name: Vidura - add github file
  copy:
    src: vidura/github_av
    dest: /home/vidura/github
    owner: vidura
    group: root
    mode: 0600

- name: Vidura - add passfile file
  copy:
    src: vidura/passfile_av
    dest: /home/vidura/passfile
    owner: vidura
    group: root
    mode: 0600
