- name: download dotfiles from git repo
  tags: dotfiles
  git:
    repo: git@github.com:belibug/dotfiles.git
    version: master
    dest: /home/bug/.dotfiles
    accept_hostkey: yes
    key_file: "{{ git_key_file }}"
  become: false

- name: stow dotfiles to repo
  tags: dotfiles
  command: "stow {{ item }} --target=/home/bug"
  args:
    chdir: /home/bug/.dotfiles/files
  with_items:
    - tmux
    - git
    - nvim
  changed_when: false
