---
- name: Quick Setup
  block:
    # Setup users
    - import_tasks: users/vidura.yml

    # setup ssh
    - import_tasks: setup_ssh.yml
      tags: configure_ssh

    - import_tasks: users/vidura.yml
      tags: bug

  become: true
  rescue:
    - debug:
        msg: "this failed"
    - set_fact: task_failed=true
