- name: install cron job (asnible-pull)
  cron:
    user: vidura
    name: "ansible-pull from git"
    minute: "*/5"
    job: "/usr/bin/ansible-pull -o -U git@github.com:belibug/ansible-pull.git --key-file /home/vidura/ansible/github --accept-host-key >> /home/vidura/ansible.log 2>&1"
